# Generated by Django 4.2.3 on 2023-07-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_tittle',
            new_name='tutorial_title',
        ),
    ]
