# Generated by Django 4.2.3 on 2023-07-25 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tutorialcategory_tutorial_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 18, 25, 50, 293795), verbose_name='date published'),
        ),
    ]
