# Generated by Django 4.2.3 on 2023-07-25 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 18, 28, 9, 253564), verbose_name='date published'),
        ),
    ]
